apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2020-09-01T19:43:46.041620
    commit.image.appsody.dev/date: Fri Jan 15 22:05:21 2021 +0530
    commit.image.appsody.dev/message: Restructuring to fix apis
    commit.stack.appsody.dev/contextDir: /incubator/java-spring-boot2
    commit.stack.appsody.dev/date: Fri Oct 9 09:28:22 2020 -0400
    commit.stack.appsody.dev/message: 'Merge pull request #347 from garypicher/updateUBIVersionForOpenJDKImage'
    description: This image is the Kabanero development container for the java-spring-boot2
      stack
    distribution-scope: public
    image.opencontainers.org/created: "2021-01-15T22:36:06+05:30"
    image.opencontainers.org/documentation: https://github.com/ibm-garage-ref-storefront/customer-ms-spring
    image.opencontainers.org/revision: e1f82742b2de9f6fa2c6e01b43aa63f66781815f-modified
    image.opencontainers.org/source: https://github.com/ibm-garage-ref-storefront/customer-ms-spring/tree/hp-fixes
    image.opencontainers.org/url: https://github.com/ibm-garage-ref-storefront/customer-ms-spring
    k8s.io/description: The Universal Base Image is designed and engineered to be
      the base layer for all of your containerized applications, middleware and utilities.
      This base image is freely redistributable, but Red Hat only supports Red Hat
      technologies through subscriptions for Red Hat products. This image is maintained
      by Red Hat and updated regularly.
    k8s.io/display-name: Red Hat Universal Base Image 8
    maintainer: Red Hat, Inc.
    name: kabanero/java-spring-boot2
    openshift.io/expose-services: ""
    openshift.io/tags: base rhel8
    redhat.com/build-host: cpt-1008.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "347"
    stack.appsody.dev/authors: Mike Andrasak <uberskigeek>, Andy Mauer <ajm01>, Scott
      Kurz <scottkurz>, Adam Wisniewski <awisniew90>
    stack.appsody.dev/configured: docker.io/kabanero/java-spring-boot2:0.3
    stack.appsody.dev/created: "2020-10-09T19:29:16Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/digest: sha256:26967ae1dbb132bb3ef942042bfa2384cd00726daabee81ce6023d979ad42995
    stack.appsody.dev/documentation: https://github.com/kabanero-io/collections/tree/master/incubator/java-spring-boot2/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 399b43ed14eb9238a8f9068f59b4bc535b62112b
    stack.appsody.dev/source: https://github.com/kabanero-io/collections/tree/master/incubator/java-spring-boot2/image
    stack.appsody.dev/tag: docker.io/kabanero/java-spring-boot2:0.3.31
    stack.appsody.dev/title: Spring Boot®
    stack.appsody.dev/url: https://github.com/kabanero-io/collections/tree/master/incubator/java-spring-boot2
    summary: Image for Kabanero java-spring-boot2 development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.2-347
    vcs-ref: 663db861f0ff7a9c526c1c169a62c14c01a32dcc
    vcs-type: git
    vendor: Kabanero
    version: 0.3.23
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: customer-ms-spring
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.31
  name: customer-ms-spring
  namespace: storefront-dev
spec:
  applicationImage: dev.local/customer-ms-spring
  createKnativeService: false
  env:
  - name: COUCHDB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: adminPassword
        name: customer-couchdb-couchdb
  - name: COUCHDB_USERNAME
    valueFrom:
      secretKeyRef:
        key: adminUsername
        name: customer-couchdb-couchdb
  - name: COUCHDB_PROTOCOL
    value: http
  - name: COUCHDB_HOST
    value: customer-couchdb-svc-couchdb
  - name: COUCHDB_PORT
    value: "5985"
  - name: COUCHDB_DATABASE
    value: customers
  - name: COUCHDB_HS256_KEY
    value: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /micro/actuator/liveness
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
  monitoring:
    endpoints:
    - path: /micro/actuator/prometheus
    labels:
      k8s-app: customer-ms-spring
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /micro/actuator/health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 15
  service:
    annotations:
      prometheus.io/path: /micro/actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
